<?php

namespace App\Tags;

use App\Amendments\Amendment;
use App\Amendments\SubAmendment;
use App\Discussions\Discussion;
use App\Model\RestModelPrimary;

class Tag extends RestModelPrimary
{
    //region constants
    const NUTZUNG_FREMDER_INHALTE_NAME = "Nutzung fremder Inhalte";
    const SOZIALE_MEDIEN_NAME = "soziale Medien";
    const KULTURELLES_ERBE_NAME = "kuturelles Erbe";
    const BILDUNG_UND_WISSENSCHAFT_NAME = "Bildung & Wissenschaft";
    const FREIHEITEN_DER_NUTZER_NAME = "Freiheiten der Nutzer";
    const RESPEKT_UND_ANERKENNUNG_NAME = "Respekt & Anerkennung";
    const RECHTEINHABERSCHAFT_NAME = "Rechteinhaberschaft";
    const DOWNLOAD_UND_STREAMING_NAME = "Download & Streaming";
    const WIRTSCHAFTLICHE_INTERESSEN_NAME = "wirtschaftliche Interessen";
    const USER_GENERATED_CONTENT_NAME = "User-Generated-Content";
    //endregion

    protected $fillable = [
        'name', 'description'
    ];

    protected $hidden = ['pivot'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::createBaseTags();
    }

    //region constant_entries

    /**
     * @return Tag
     */
    public static function getNutzungFremderInhalte() : Tag
    {
        return Tag::where('name', '=', self::NUTZUNG_FREMDER_INHALTE_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getSozialeMedien() : Tag
    {
        return Tag::where('name', '=', self::SOZIALE_MEDIEN_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getKulturellesErbe() : Tag
    {
        return Tag::where('name', '=', self::KULTURELLES_ERBE_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getBildungUndWissenschaft() : Tag
    {
        return Tag::where('name', '=', self::BILDUNG_UND_WISSENSCHAFT_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getFreiheitenDerNutzer() : Tag
    {
        return Tag::where('name', '=', self::FREIHEITEN_DER_NUTZER_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getRespektUndAnerkennung() : Tag
    {
        return Tag::where('name', '=', self::RESPEKT_UND_ANERKENNUNG_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getRechteinhaberschaft() : Tag
    {
        return Tag::where('name', '=', self::RECHTEINHABERSCHAFT_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getDownloadUndStreaming() : Tag
    {
        return Tag::where('name', '=', self::DOWNLOAD_UND_STREAMING_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getWirtschaftlicheInteressen() : Tag
    {
        return Tag::where('name', '=', self::WIRTSCHAFTLICHE_INTERESSEN_NAME)->first();
    }

    /**
     * @return Tag
     */
    public static function getUserGeneratedContent() : Tag
    {
        return Tag::where('name', '=', self::USER_GENERATED_CONTENT_NAME)->first();
    }
    //endregion

    function getApiFriendlyType(): string
    {
        return 'tag';
    }

    public function getResourcePath()
    {
        return '/tags/' . $this->id;
    }

    //region relations
    public function taggables()
    {
        return $this->with(['discussions', 'amendments', 'sub_amendments']);    //Not sure if this works
    }

    public function discussions()
    {
        return $this->morphedByMany(Discussion::class, 'taggable', 'taggables');
    }

    public function amendments()
    {
        return $this->morphedByMany(Amendment::class, 'taggable', 'taggables');
    }

    public function sub_amendments()
    {
        return $this->morphedByMany(SubAmendment::class, 'taggable', 'taggables');
    }
    //endregion

    /**
     * return @void
     */
    private static function createBaseTags() : void
    {
        Tag::firstOrCreate(['name' => Tag::NUTZUNG_FREMDER_INHALTE_NAME, 'description' => 'Alles rund um die Nutzung fremder Inhalte']);
        Tag::firstOrCreate(['name' => Tag::SOZIALE_MEDIEN_NAME, 'description' => 'Alles rund um Soziale Medien']);
        Tag::firstOrCreate(['name' => Tag::KULTURELLES_ERBE_NAME, 'description' => 'Alles rund um kulturelles Erbe']);
        Tag::firstOrCreate(['name' => Tag::BILDUNG_UND_WISSENSCHAFT_NAME, 'description' => 'Alles rund um Bildung und Wissenschaft']);
        Tag::firstOrCreate(['name' => Tag::FREIHEITEN_DER_NUTZER_NAME, 'description' => 'Alles rund um Freiheiten der Nutzer']);
        Tag::firstOrCreate(['name' => Tag::RESPEKT_UND_ANERKENNUNG_NAME, 'description' => 'Alles rund um Respekt und Anerkennung']);
        Tag::firstOrCreate(['name' => Tag::RECHTEINHABERSCHAFT_NAME, 'description' => 'Alles rund um Rechteinhaberschaft']);
        Tag::firstOrCreate(['name' => Tag::DOWNLOAD_UND_STREAMING_NAME, 'description' => 'Alles rund um Downloads und Streaming']);
        Tag::firstOrCreate(['name' => Tag::WIRTSCHAFTLICHE_INTERESSEN_NAME, 'description' => 'Alles rund um wirtschaftliche Interessen']);
        Tag::firstOrCreate(['name' => Tag::USER_GENERATED_CONTENT_NAME, 'description' => 'Alles rund um User Generated Content']);
    }
}
